global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: default_scraping
    scheme: http
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["service:8080"]