/*
 * This file is generated by jOOQ.
 */
package dev.abarmin.jooq.db;


import dev.abarmin.jooq.db.tables.Person;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>PUBLIC.PERSON</code>.
     */
    public static final Person PERSON = Person.PERSON;
}
