spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
          custom-auth:
            client-id: abcd-client-id
            client-secret: abcd-client-secret

management:
  endpoints:
    web:
      exposure:
        include: '*'

#logging:
#  level:
#    org.springframework.security: TRACE