spring:
  datasource:
    url: jdbc:h2:file:./build/demo-db
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
integration:
  balance-service:
    endpoint:
      base-url: http://localhost:8080/balance/